### ISSUE TITLE
Unable to run specs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#24]
**Expected behavior**
Should be able to run specs

**Actual behavior**
Getting the following error
```
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from getgauge import api
ModuleNotFoundError: No module named 'getgauge'
Failed to start gauge API: Runner with pid 12876 quit unexpectedly(exit status 1).
```
**Steps to replicate**
* `gauge init python`
Downloading python.zip
...
Copying Gauge template python to current directory ...
Successfully initialized the project. Run specifications with "gauge run specs/".
* `gauge run specs`
Getting the above error

**Version**
`python`
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32

```
Gauge version: 0.9.8.nightly-2018-01-19
Commit Hash: 0c66ca4

Plugins
----------
python (0.2.3)
```

**Comment by BugDiver** [comment]
@sguptatw After installing `python` runner, you need to install the `getgauge` python package.
You can run `pip install getgauge` to do so.

**Comment by sguptatw** [comment]
@BugDiver : Can this be part of the installation? Or can this message be given after installation?

**Comment by zdman135** [comment]
@BugDiver - `pip install getgauge` installing pip did not solve my problem
I even tried using `sudo` instead of installing it as `--user`

I did the following:
1) installed gauge - `dnf install gauge`
verified with `gauge -v`

2) installed python runner - `gauge install python`
verified with `gauge -v`

3) Installed getgauge - `pip install getgauge --user`
verified with `pip show getgauge`

4) Initialized gauge - `gauge init python`
5) Run specs - `gauge run specs`

`gauge run specs/
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from getgauge import api
ImportError: cannot import name api
Failed to start gauge API: Runner with pid 16574 quit unexpectedly(exit status 1).
`

I am on fedora 27 using python 2.7

Any Ideas?

**Comment by BugDiver** [comment]
@zdman135  Could you please provide some more information about your environment?
* What `gauge` version are you using?
* What `gauge-python` version are you using?
* What is the version of `getgauge` PyPI package?

You can run following commands to find these -
* Run `gauge version` to get `gauge` and `gauge-python` version
* Run `pip show getgauge` to check `getgauge` package version

**Comment by zdman135** [comment]
@BugDiver 
### Description
**Expected Behavior:** when I run `gauge run specs` it will run the specs
**Actual Behavior:** when I run `gauge run specs` it produces an error:

`gauge run specs/ Traceback (most recent call last): File "start.py", line 6, in <module> from getgauge import api ImportError: cannot import name api Failed to start gauge API: Runner with pid 16574 quit unexpectedly(exit status 1).`

### Steps to reproduce
1. Installed gauge
2. Installed python runner
3. Installed getgauge
4. Initialized gauge in a directory
5. Run generated gauge specs

### Information that will help us debug

* Gauge version - Gauge version: 0.9.7 - Commit Hash: bc9784c
* Gauge Python plugin version - python (0.2.3)
* Python version - Python 2.7.14
* `getgauge` package version, run `pip3 show getgauge` to get it
Name: getgauge
Version: 0.2.5
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /home/shark/.local/lib/python2.7/site-packages
Requires: protobuf, redBaron, ptvsd
* OS information
Fedora release 27 (Twenty Seven) with all the latest updates

I also used another machine - fresh installed Fedora 27 and installed all the latest updates from Fedora, and ran the exact steps above, and still received the same error.

**Comment by zdman135** [comment]
Thanks @BugDiver  - issue has been fixed.
We found the issue to be the `getgauge` version I was using was 0.2.5
And the `python-gauge` version I was using was 0.2.3

I proceeded to downgrade the `getgauge` version to 0.2.3
That appeared to fix my issue and error.

Thanks!
