### ISSUE TITLE
Clicking on the stacktrace takes to the next line

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#64]
**Expected behavior**
Clicking on the stacktrace should take the user to  the code line with the issue

**Actual behavior**
It takes the user to the next line of the code with the issue

**Steps to replicate**
* Create a new `gauge-python` project
* Add a new step. Generate stub implementation
* Run the specs
* On VSCode console click on the stacktrace with the error in impl file
> The user is taken to the next line where the error occurred.

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-26
Commit Hash: 5bd699e

Plugins
-------
python (0.3.0.nightly-2018-04-26)
```

**Comment by riju91** [comment]
In the Python stacktrace, the file name and the line number comes separately. For example 
```File "/Users/user/tmp/py-test/step_impl/step_implementation.py", line 10, in hello``` so vscode only opens the file without considering the line number. Since we generated a step in the steps to replicate, the cursor was last located at the line next of the step implementation and hence when we open the file, we find the cursor there, but if we move it so some other position and click on the stacktrace to open the file, we would find the cursor to be there
